## Imports and Supabase Connection

In [70]:
import os
import pandas as pd
from supabase import create_client
from dotenv import load_dotenv
from pathlib import Path
import plotly.express as px
import statsmodels.api as sm
import statsmodels.formula.api as smf

%matplotlib inline
# Resolve the project root (one level above `/notebooks`).
project_root = Path.cwd().parent
env_path = project_root / ".env"

load_dotenv(dotenv_path=env_path, override=True)

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# Optional sanity check.
print("Loaded key starts with:", SUPABASE_KEY[:5])

Loaded key starts with: eyJhb

## Incident

In [71]:
# Read the incident table in 1,000-row pages to avoid timeouts and memory spikes.
page_size = 1000
# Accumulate rows until Supabase returns an empty page.
all_rows = []
start = 0

while True:
    response = (
        supabase
        .table("incident")
        .select("*")
        .order("Incident_ID")   # Required for stable pagination.
        .range(start, start + page_size - 1)
        .execute()
    )

    data = response.data
    if not data:
        break

    all_rows.extend(data)
    start += page_size

incident_df = pd.DataFrame(all_rows)
incident_df["Number_Victims"] = pd.to_numeric(incident_df["Number_Victims"], errors="coerce")

# Quick validation of total row count.
print (len(incident_df))
print (incident_df.head(2))

3136
     Incident_ID  Month  Day  Year                       Date  \
0  19660311NCIRC      3   11  1966  1966-03-11T00:00:00+00:00
1  19660314TXCAW      3   14  1966  1966-03-14T00:00:00+00:00

                             School Victims_Killed Victims_Wounded  \
0  Irwing Avenue Junior High School              0               1
1                Carver High School              1               0

   Number_Victims Shooter_Killed  ... Preplanned SRO_School  \
0               1              0  ...         No
1               1              0  ...         No        Yes

  Security_Screening     Screening_Outcome Shots_Fired School_Lockdown  \
0                                                    7
1       Armed Guards  Outside/Off-Property           3

         LAT         LNG Campus_Type Zipcode
0  35.237069  -80.850227               28202
1   31.57954  -97.130303               76704

[2 rows x 50 columns]

# Model Exploring

## Incidents

### Apply the best subset selection approach to incident data. We wish to predict risk based on a variety of features/predictors

In [72]:
valid_states = {
"AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
"HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
"MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
"NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
"SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","DC"
}

invalid = incident_df[~incident_df["State"].isin(valid_states)]
invalid["State"].unique()

<StringArray>
[             'Winter',             'Houston',         'Rogersville',
           'Hahnville',             'Artesia',           'Pensacola',
           'St. Louis',              'Dallas',          'Fort Worth',
              'Spring',                'Fall',            'Hartford',
            'Anniston',               'Miami',              'Aldine',
            'Portland',        'New Rochelle',        'Indianapolis',
               'Tampa',             'Bristol',          'Fort Myers',
            'Winnetka',             'Detroit',                'Oahu',
         'Baton Rouge',         'Port Arthur',      'Virginia Beach',
            'Stockton',          'Washington',             'Slidell',
           'Rock Hill',              'Merced',            'Amarillo',
          'Montgomery',                   '4',              'Summer',
 'San Fernando Valley',          'Manchester',            'New York',
               'Omaha',                  'VI',                    '',
          'Harrington',           'Lexington']
Length: 44, dtype: str

## Sample Restriction (1987–Present)

The panel is restricted to 1987 onward due to a structural break in the underlying data-generating process prior to 1987.

Pre-1987 observations are not comparable in measurement, reporting coverage, and policy codification. Including those years would violate panel homogeneity assumptions and introduce non-structural noise into fixed effects and dynamic specifications.

This restriction is not outcome-based filtering. It is a data consistency adjustment to ensure:

- Comparable incident classification
- Consistent enrollment coverage
- Reliable policy coding
- Stable variance structure

All models are therefore estimated on the 1987–present balanced policy-enrollment panel.

## Incidents from 1987

In [73]:
incident_df_from_1987 = incident_df[incident_df["State"].isin(valid_states)]
print(incident_df_from_1987.shape) # incident_df_from_1987.shape
print(incident_df_from_1987["State"].unique())

(3070, 50)
<StringArray>
['NC', 'TX', 'CA', 'NY', 'FL', 'PA', 'MN', 'TN', 'IL', 'VT', 'HI', 'OK', 'KY',
 'DC', 'WI', 'OH', 'AR', 'DE', 'UT', 'ID', 'IA', 'MI', 'NJ', 'AZ', 'VA', 'MD',
 'NM', 'LA', 'NV', 'IN', 'AL', 'MO', 'CT', 'SC', 'GA', 'CO', 'MA', 'WV', 'MS',
 'OR', 'MT', 'KS', 'WA', 'WY', 'RI', 'NH', 'NE', 'AK', 'ME', 'SD', 'ND']
Length: 51, dtype: str

In [74]:
# incident count per state-year combination
incident_counts = (
    incident_df_from_1987
    .groupby(["State", "Year"])
    .size()
    .reset_index(name="incident_count")
)

# Ensure Victims_Killed is numeric before aggregation
incident_df_from_1987["Victims_Killed"] = pd.to_numeric(
    incident_df_from_1987["Victims_Killed"],
    errors="coerce"
)

# Replace any non-numeric values with 0
incident_df_from_1987["Victims_Killed"] = (
    incident_df_from_1987["Victims_Killed"].fillna(0)
)

In [75]:
# supabase.table("state_year_enrollment").select("*").execute()

In [76]:
response = supabase.table("Enrollment Data Final").select("*").limit(1).execute(); print(response.data)

[{'school_id': 601195, 'state': 'California', 'year': 1996, 'total_students': 154}]

In [77]:
all_rows = []
start = 0
batch_size = 1000

while True:
    response = (
        supabase
        .table("enrollment_state_year_mat")
        .select("*")
        .range(start, start + batch_size - 1)
        .execute()
    )
    
    data = response.data
    
    if not data:
        break
        
    all_rows.extend(data)
    start += batch_size

enrollment_df = pd.DataFrame(all_rows)

print(enrollment_df.shape)

(2548, 3)

In [78]:
# Keep only incident years that exist in enrollment data
incident_counts = incident_counts[
    incident_counts["Year"] >= 1987
]

In [79]:
enrollment_df

                     state  year  total_students
0             RHODE ISLAND  2020           10006
1                Louisiana  2025          569440
2                  Montana  1999          160294
3                  Georgia  2015         1721666
4             Rhode Island  2016          139409
...                    ...   ...             ...
2543  District of Columbia  2013           75819
2544              Kentucky  2014          683957
2545               GEORGIA  2020           87127
2546  DISTRICT OF COLUMBIA  2015            1671
2547              ILLINOIS  2025           76904

[2548 rows x 3 columns]

In [80]:
# Convert full state names to uppercase for consistent mapping
enrollment_df["state"] = enrollment_df["state"].str.upper()


# Map full state names to two-letter abbreviations
state_abbrev = {
    'ALABAMA': 'AL', 'ALASKA': 'AK', 'ARIZONA': 'AZ', 'ARKANSAS': 'AR',
    'CALIFORNIA': 'CA', 'COLORADO': 'CO', 'CONNECTICUT': 'CT',
    'DELAWARE': 'DE', 'DISTRICT OF COLUMBIA': 'DC', 'FLORIDA': 'FL',
    'GEORGIA': 'GA', 'HAWAII': 'HI', 'IDAHO': 'ID', 'ILLINOIS': 'IL',
    'INDIANA': 'IN', 'IOWA': 'IA', 'KANSAS': 'KS', 'KENTUCKY': 'KY',
    'LOUISIANA': 'LA', 'MAINE': 'ME', 'MARYLAND': 'MD',
    'MASSACHUSETTS': 'MA', 'MICHIGAN': 'MI', 'MINNESOTA': 'MN',
    'MISSISSIPPI': 'MS', 'MISSOURI': 'MO', 'MONTANA': 'MT',
    'NEBRASKA': 'NE', 'NEVADA': 'NV', 'NEW HAMPSHIRE': 'NH',
    'NEW JERSEY': 'NJ', 'NEW MEXICO': 'NM', 'NEW YORK': 'NY',
    'NORTH CAROLINA': 'NC', 'NORTH DAKOTA': 'ND', 'OHIO': 'OH',
    'OKLAHOMA': 'OK', 'OREGON': 'OR', 'PENNSYLVANIA': 'PA',
    'RHODE ISLAND': 'RI', 'SOUTH CAROLINA': 'SC',
    'SOUTH DAKOTA': 'SD', 'TENNESSEE': 'TN', 'TEXAS': 'TX',
    'UTAH': 'UT', 'VERMONT': 'VT', 'VIRGINIA': 'VA',
    'WASHINGTON': 'WA', 'WEST VIRGINIA': 'WV',
    'WISCONSIN': 'WI', 'WYOMING': 'WY'
}

# Create State column matching incident dataset
enrollment_df["State"] = enrollment_df["state"].map(state_abbrev)

# Rename year column for merge consistency
enrollment_df = enrollment_df.rename(columns={"year": "Year"})

In [81]:
# Keep only the larger enrollment value per state–year
enrollment_df = (
    enrollment_df
    .sort_values("total_students", ascending=False)
    .drop_duplicates(["State", "Year"])
)

In [82]:
# Merge incident counts with enrollment data on State and Year
merged_df_table = incident_counts.merge(
    enrollment_df[["State", "Year", "total_students"]],
    on=["State", "Year"],
    how="left"
)

# Check for any unmatched rows after merge
print(merged_df_table["total_students"].isna().sum())

# Compute incident rate per 100,000 students
merged_df_table["incident_rate_per_100k"] = (
    merged_df_table["incident_count"] / merged_df_table["total_students"]
) * 100000

# Inspect result
print(merged_df_table.head())

0
  State  Year  incident_count  total_students  incident_rate_per_100k
0    AK  1997               1          129919                0.769710
1    AK  2005               1          131701                0.759296
2    AK  2018               1          129660                0.771248
3    AK  2019               1          127641                0.783447
4    AK  2022               1          126457                0.790783

This notebook focuses on state-year incident risk, not conditional harm severity.

In [83]:
incident_df_from_1987 = incident_df_from_1987[incident_df_from_1987["State"].str.match(r"^[A-Z]{2}$", na=False)]
print("Remaining rows:", len(incident_df_from_1987))

Remaining rows: 3070

In [84]:
valid_states = incident_df_from_1987["State"].str.match(r"^[A-Z]{2}$", na=False)
print("Valid rows:", valid_states.sum())
print("Invalid rows:", (~valid_states).sum())

Valid rows: 3070
Invalid rows: 0

In [85]:
print(incident_df_from_1987.head())

     Incident_ID  Month  Day  Year                       Date  \
0  19660311NCIRC      3   11  1966  1966-03-11T00:00:00+00:00
1  19660314TXCAW      3   14  1966  1966-03-14T00:00:00+00:00
2  19660324CACAM      3   24  1966  1966-03-24T00:00:00+00:00
3  19660328CAJOL      3   28  1966  1966-03-28T00:00:00+00:00
4  19660427NYBAB      4   27  1966  1966-04-27T00:00:00+00:00

                             School  Victims_Killed Victims_Wounded  \
0  Irwing Avenue Junior High School               0               1
1                Carver High School               1               0
2    Camino Pablo Elementary School               3               0
3                Jordan High School               0               1
4             Bay Shore High School               1               0

   Number_Victims Shooter_Killed  ... Preplanned SRO_School  \
0               1              0  ...         No
1               1              0  ...         No        Yes
2               3              1  ...         No
3               1              0  ...         No        Yes
4               1              0  ...         No

  Security_Screening     Screening_Outcome Shots_Fired School_Lockdown  \
0                                                    7
1       Armed Guards  Outside/Off-Property           3
2                     Outside/Off-Property          99
3       Armed Guards  Outside/Off-Property          99
4                                                    1

         LAT          LNG Campus_Type Zipcode
0  35.237069   -80.850227               28202
1   31.57954   -97.130303               76704
2  37.821031  -122.121426               94575
3  33.944239   -118.23056               90002
4  40.731985   -73.254938               11706

[5 rows x 50 columns]

In [86]:
print(merged_df_table["incident_count"].describe())

count    861.000000
mean       3.191638
std        3.745599
min        1.000000
25%        1.000000
50%        2.000000
75%        4.000000
max       25.000000
Name: incident_count, dtype: float64

In [87]:
print(merged_df_table["total_students"].describe())

count    8.610000e+02
mean     1.339581e+06
std      1.313322e+06
min      5.003200e+04
25%      5.573810e+05
50%      8.762130e+05
75%      1.662643e+06
max      6.322586e+06
Name: total_students, dtype: float64

In [88]:
import numpy as np

merged_df_table["log_enrollment"] = np.log(merged_df_table["total_students"])
print(merged_df_table["log_enrollment"].describe())

count    861.000000
mean      13.701213
std        0.947233
min       10.820418
25%       13.231004
50%       13.683364
75%       14.323919
max       15.659639
Name: log_enrollment, dtype: float64

In [89]:
incident_agg = (
    incident_df_from_1987
    .groupby(["State","Year"], as_index=False)
    .size()
    .rename(columns={"size": "incident_count"})
)

merged_df_table = enrollment_df.merge(
    incident_agg,
    on=["State","Year"],
    how="left"
)

merged_df_table["incident_count"] = merged_df_table["incident_count"].fillna(0)

print(merged_df_table.shape)
print((merged_df_table["incident_count"] == 0).sum())

(1989, 5)
1128

In [90]:
merged_df_table["log_enrollment"] = np.log(merged_df_table["total_students"])
print(merged_df_table.head())

        state  Year  total_students State  incident_count  log_enrollment
0  CALIFORNIA  2005         6322586    CA             6.0       15.659639
1  CALIFORNIA  2006         6312103    CA             4.0       15.657979
2  CALIFORNIA  2004         6298928    CA             7.0       15.655890
3  CALIFORNIA  2007         6274813    CA             5.0       15.652054
4  CALIFORNIA  2003         6244403    CA             4.0       15.647196

In [91]:
merged_df_table = merged_df_table.drop(columns=["state"])
print(merged_df_table.columns)

Index(['Year', 'total_students', 'State', 'incident_count', 'log_enrollment'], dtype='str')

In [92]:
all_rows = []
start = 0
batch_size = 1000

while True:
    response = (
        supabase
        .table("background_check_binary")
        .select("*")
        .range(start, start + batch_size - 1)
        .execute()
    )
    
    data = response.data
    
    if not data:
        break
        
    all_rows.extend(data)
    start += batch_size

bg_df = pd.DataFrame(all_rows)

print(bg_df.shape)

(2295, 3)

In [93]:
policy_tables = [
    "background_check_binary",
    "permit_to_purchase_binary",
    "prohibited_possessor_binary",
    "waiting_period_binary",
    "registration_binary",
    "child_access_binary",
    "safety_training_binary",
    "report_stolen_lost_binary",
    "firearm_sales_retrictions_binary",
    "k12_settings_binary"
]

policy_dfs = {}

for table in policy_tables:
    all_rows = []
    start = 0
    batch_size = 1000

    while True:
        response = (
            supabase
            .table(table)
            .select("*")
            .range(start, start + batch_size - 1)
            .execute()
        )
        data = response.data
        if not data:
            break
        all_rows.extend(data)
        start += batch_size

    policy_dfs[table] = pd.DataFrame(all_rows)

print({k: v.shape for k, v in policy_dfs.items()})

{'background_check_binary': (2295, 3), 'permit_to_purchase_binary': (2115, 3), 'prohibited_possessor_binary': (2115, 3), 'waiting_period_binary': (2295, 3), 'registration_binary': (2295, 3), 'child_access_binary': (1620, 3), 'safety_training_binary': (405, 3), 'report_stolen_lost_binary': (765, 3), 'firearm_sales_retrictions_binary': (2295, 3), 'k12_settings_binary': (315, 3)}

In [94]:
for name, df in policy_dfs.items():
    merged_df_table = merged_df_table.merge(
        df,
        left_on=["State","Year"],
        right_on=["state","year"],
        how="left"
    )
    merged_df_table = merged_df_table.drop(columns=["state","year"])

# Replace NaN with 0 for all policy indicators
policy_cols = [col for col in merged_df_table.columns if col.endswith("_law")]
merged_df_table[policy_cols] = merged_df_table[policy_cols].fillna(0)

print(merged_df_table.shape)
print(len(policy_cols), "policy variables merged")

(1989, 15)
10 policy variables merged

## State-Year Risk Model

### Objective

Estimate the association between state firearm policies and the **risk of school shooting incidents**, measured at the state-year level.

Risk is operationalized as the incident rate:

\[
\text{Risk}_{s,t} =
\frac{\text{Incident Count}_{s,t}}{\text{Student Enrollment}_{s,t}}
\]

For descriptive visuals, this rate is scaled to incidents per 100,000 students.

---

### Data Structure

The analysis uses a state-year panel with:

- All U.S. states plus DC  
- Years in the study window  
- Zero-incident state-years retained  
- Total student enrollment as the exposure measure  
- Binary firearm policy indicators  

Each observation is one **state-year**.

---

### Modeling Strategy

A **Negative Binomial regression** is used because the dependent variable is a nonnegative count with overdispersion and many zeros.

The model is estimated with:

- Outcome: `incident_count`  
- Offset: `log_enrollment`  
- Policy indicators as covariates  

Including `log(total_students)` as an offset means the model is estimating the **incident rate**, not a raw count relationship.

---

### Specification

\[
\log(E[Y_{s,t}]) =
\beta_0 +
\beta_k \text{Policy}_{k,s,t} +
\log(\text{Enrollment}_{s,t})
\]

where `Y_{s,t}` is the number of incidents in state `s` and year `t`. Rearranging the offset form shows that the model is equivalent to modeling risk per student.

---

### Interpretation

Exponentiated coefficients are **Incidence Rate Ratios (IRRs)**:

- IRR < 1 implies lower incident risk  
- IRR > 1 implies higher incident risk  

Substantively, the question is whether policies are associated with fewer incidents relative to enrollment exposure.

---

### Scope

This notebook is limited to **risk of incident occurrence**. Outcomes based on victim counts or victims per incident are intentionally excluded from the main framework.

In [95]:
formula = """
incident_count ~ 
background_check_law +
permit_to_purchase_law +
prohibited_possessor_law +
waiting_period_law +
registration_law +
child_access_law +
safety_training_law +
report_stolen_lost_law +
firearm_sales_retrictions_law +
k12_settings_law +
C(State) +
C(Year)
"""

model_joint = smf.glm(
    formula=formula,
    data=merged_df_table,
    family=sm.families.NegativeBinomial(),
    offset=merged_df_table["log_enrollment"]
).fit()

print(model_joint.summary())

/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:         incident_count   No. Observations:                 1989
Model:                            GLM   Df Residuals:                     1890
Model Family:        NegativeBinomial   Df Model:                           98
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2247.4
Date:                Wed, 08 Apr 2026   Deviance:                       1055.1
Time:                        12:47:49   Pearson chi2:                 1.36e+03
No. Iterations:                     9   Pseudo R-squ. (CS):             0.4500
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                       -15.0842      0.591    -25.524      0.000     -16.243     -13.926
C(State)[T.AL]                    0.6980      0.534      1.307      0.191      -0.349       1.745
C(State)[T.AR]                    0.2997      0.546      0.549      0.583      -0.771       1.370
C(State)[T.AZ]                   -0.5102      0.548     -0.931      0.352      -1.585       0.564
C(State)[T.CA]                    0.3736      0.551      0.678      0.498      -0.706       1.453
C(State)[T.CO]                    0.0651      0.558      0.117      0.907      -1.028       1.159
C(State)[T.CT]                    0.1226      0.593      0.207      0.836      -1.039       1.284
C(State)[T.DC]                    2.8558      0.582      4.911      0.000       1.716       3.996
C(State)[T.DE]                    1.0582      0.592      1.788      0.074      -0.102       2.218
C(State)[T.FL]                    0.3895      0.538      0.724      0.469      -0.665       1.444
C(State)[T.GA]                    0.4995      0.547      0.912      0.362      -0.573       1.572
C(State)[T.HI]                   -0.2006      0.713     -0.281      0.779      -1.599       1.198
C(State)[T.IA]                   -0.1762      0.585     -0.301      0.763      -1.324       0.971
C(State)[T.ID]                    0.1150      0.612      0.188      0.851      -1.085       1.315
C(State)[T.IL]                    0.4333      0.540      0.803      0.422      -0.625       1.492
C(State)[T.IN]                    0.0874      0.558      0.157      0.875      -1.006       1.180
C(State)[T.KS]                    0.2220      0.558      0.398      0.691      -0.871       1.315
C(State)[T.KY]                    0.1306      0.570      0.229      0.819      -0.986       1.247
C(State)[T.LA]                    1.1644      0.527      2.208      0.027       0.131       2.198
C(State)[T.MA]                   -0.1887      0.602     -0.313      0.754      -1.369       0.992
C(State)[T.MD]                    0.5033      0.550      0.916      0.360      -0.574       1.580
C(State)[T.ME]                   -0.3321      0.654     -0.508      0.611      -1.613       0.949
C(State)[T.MI]                    0.7587      0.539      1.407      0.159      -0.298       1.815
C(State)[T.MN]                   -0.3871      0.573     -0.676      0.499      -1.510       0.736
C(State)[T.MO]                    0.1032      0.552      0.187      0.852      -0.978       1.185
C(State)[T.MS]                    0.6270      0.564      1.111      0.267      -0.479       1.733
C(State)[T.MT]                    0.4839      0.616      0.786      0.432      -0.723       1.691
C(State)[T.NC]                    0.3403      0.540      0.631      0.528      -0.717       1.398
C(State)[T.ND]                   -0.4223      0.735     -0.574      0.566      -1.863       1.018
C(State)[T.NE]                    0.1139      0.592      0.192      0.847      -1.046       1.274
C(State)[T.NH]                   -0.1655      0.650     -0.254      0.799      -1.440       1.109
C(State)[T.NJ]                   -0.5505      0.582     -0.945      0.345      -1.692       0.591
C(State)[T.NM]                    0.4722      0.584      0.808      0.419      -0.672       1.617
C(State)[T.NV]                    0.1358      0.581      0.234      0.815      -1.003       1.274
C(State)[T.NY]                    0.1009      0.547      0.184      0.854      -0.972       1.174
C(State)[T.OH]                    0.5449      0.541      1.007      0.314      -0.516       1.605
C(State)[T.OK]                   -0.0431      0.559     -0.077      0.939      -1.138       1.052
C(State)[T.OR]                    0.2283      0.551      0.414      0.679      -0.851       1.308
C(State)[T.PA]                    0.3376      0.536      0.630      0.528      -0.712       1.387
C(State)[T.RI]                    0.3169      0.678      0.467      0.640      -1.013       1.646
C(State)[T.SC]                    0.5645      0.527      1.072      0.284      -0.467       1.597
C(State)[T.SD]                    0.1271      0.673      0.189      0.850      -1.192       1.446
C(State)[T.TN]                    0.8612      0.549      1.569      0.117      -0.215       1.937
C(State)[T.TX]                    0.2495      0.522      0.478      0.633      -0.774       1.273
C(State)[T.UT]                    0.1918      0.563      0.341      0.733      -0.911       1.295
C(State)[T.VA]                   -0.0816      0.564     -0.145      0.885      -1.187       1.024
C(State)[T.VT]                    0.2243      0.706      0.318      0.751      -1.160       1.609
C(State)[T.WA]                    0.4355      0.530      0.822      0.411      -0.602       1.473
C(State)[T.WI]                   -0.1868      0.561     -0.333      0.739      -1.286       0.912
C(State)[T.WV]                   -0.5434      0.635     -0.856      0.392      -1.788       0.701
C(State)[T.WY]                   -1.2654      1.119     -1.131      0.258      -3.459       0.928
C(Year)[T.1988]                   0.2780      0.401      0.693      0.488      -0.509       1.065
C(Year)[T.1989]                  -0.2015      0.432     -0.467      0.641      -1.047       0.644
C(Year)[T.1990]                  -0.1332      0.428     -0.311      0.755      -0.972       0.705
C(Year)[T.1991]                   0.1722      0.408      0.422      0.673      -0.627       0.971
C(Year)[T.1992]                   0.2752      0.401      0.686      0.493      -0.511       1.061
C(Year)[T.1993]                   0.7839      0.379      2.066      0.039       0.040       1.528
C(Year)[T.1994]                   0.6685      0.438      1.527      0.127      -0.189       1.526
C(Year)[T.1995]                   0.2476      0.457      0.542      0.588      -0.648       1.143
C(Year)[T.1996]                   0.0447      0.467      0.096      0.924      -0.871       0.960
C(Year)[T.1997]                   0.1083      0.463      0.234      0.815      -0.799       1.016
C(Year)[T.1998]                   0.4787      0.446      1.073      0.283      -0.396       1.353
C(Year)[T.1999]                   0.2091      0.457      0.457      0.648      -0.687       1.106
C(Year)[T.2000]                   0.3440      0.452      0.761      0.447      -0.542       1.230
C(Year)[T.2001]                   0.0648      0.466      0.139      0.890      -0.849       0.979
C(Year)[T.2002]                  -0.1405      0.478     -0.294      0.769      -1.077       0.796
C(Year)[T.2003]                   0.5693      0.443      1.285      0.199      -0.299       1.437
C(Year)[T.2004]                   0.4788      0.446      1.073      0.283      -0.395       1.353
C(Year)[T.2005]                   0.7859      0.418      1.881      0.060      -0.033       1.605
C(Year)[T.2006]                   1.1090      0.409      2.715      0.007       0.308       1.910
C(Year)[T.2007]                   0.7063      0.423      1.670      0.095      -0.122       1.535
C(Year)[T.2008]                   0.4575      0.434      1.054      0.292      -0.393       1.308
C(Year)[T.2009]                   0.4443      0.436      1.019      0.308      -0.411       1.299
C(Year)[T.2010]                  -0.2678      0.476     -0.562      0.574      -1.201       0.666
C(Year)[T.2011]                  -0.2781      0.477     -0.583      0.560      -1.213       0.657
C(Year)[T.2012]                   0.0113      0.458      0.025      0.980      -0.886       0.909
C(Year)[T.2013]                   0.4475      0.440      1.018      0.309      -0.414       1.309
C(Year)[T.2014]                   1.0450      0.420      2.488      0.013       0.222       1.868
C(Year)[T.2015]                   0.7009      0.431      1.626      0.104      -0.144       1.546
C(Year)[T.2016]                   1.0338      0.421      2.454      0.014       0.208       1.860
C(Year)[T.2017]                   1.0432      0.422      2.474      0.013       0.217       1.870
C(Year)[T.2018]                   2.0415      0.405      5.045      0.000       1.248       2.835
C(Year)[T.2019]                   1.9863      0.409      4.857      0.000       1.185       2.788
C(Year)[T.2020]                   1.8622      0.411      4.530      0.000       1.057       2.668
C(Year)[T.2021]                   2.7623      0.404      6.834      0.000       1.970       3.554
C(Year)[T.2022]                   2.9615      0.405      7.317      0.000       2.168       3.755
C(Year)[T.2023]                   3.0774      0.406      7.572      0.000       2.281       3.874
C(Year)[T.2024]                   3.1400      0.401      7.839      0.000       2.355       3.925
C(Year)[T.2025]                   2.1758      0.409      5.316      0.000       1.374       2.978
background_check_law             -0.4003      0.236     -1.697      0.090      -0.863       0.062
permit_to_purchase_law            0.2398      0.168      1.431      0.152      -0.089       0.568
prohibited_possessor_law          0.2047      0.160      1.280      0.200      -0.109       0.518
waiting_period_law               -1.4190      1.046     -1.356      0.175      -3.470       0.632
registration_law                  1.6531      1.053      1.570      0.117      -0.411       3.717
child_access_law                  0.0445      0.159      0.281      0.779      -0.266       0.355
safety_training_law              -0.1156      0.226     -0.512      0.608      -0.558       0.327
report_stolen_lost_law           -0.3031      0.175     -1.728      0.084      -0.647       0.041
firearm_sales_retrictions_law     0.0096      0.171      0.056      0.955      -0.325       0.344
k12_settings_law                 -0.3961      0.259     -1.527      0.127      -0.905       0.112
=================================================================================================

In [96]:
import numpy as np
print(np.exp(model_joint.params))

Intercept                        2.811915e-07
C(State)[T.AL]                   2.009817e+00
C(State)[T.AR]                   1.349513e+00
C(State)[T.AZ]                   6.003576e-01
C(State)[T.CA]                   1.453006e+00
                                     ...
child_access_law                 1.045549e+00
safety_training_law              8.908755e-01
report_stolen_lost_law           7.385070e-01
firearm_sales_retrictions_law    1.009689e+00
k12_settings_law                 6.729423e-01
Length: 99, dtype: float64

## Two-Way Fixed Effects Risk Model

### Objective

Strengthen the risk model by controlling for both:

- **State fixed effects** for time-invariant state characteristics
- **Year fixed effects** for nationwide shocks and trend shifts

This produces a two-way fixed effects specification for **enrollment-adjusted incident risk**.

---

### Why Add Year Fixed Effects?

Year effects absorb national movements in school shooting risk that are shared across states, including:

- Broad upward time trends  
- Reporting and classification changes  
- National policy and media shocks  
- Other macro-level temporal shifts  

Without year controls, policy coefficients can incorrectly absorb nationwide trend effects.

---

### Specification

The model includes:

- `C(State)` for baseline state differences  
- `C(Year)` for common year shocks  
- Binary policy indicators  
- `log(total_students)` as the exposure offset  

\[
\log(E[Y_{s,t}]) =
\beta_0 +
\beta_k \text{Policy}_{k,s,t} +
\gamma_s +
\delta_t +
\log(\text{Enrollment}_{s,t})
\]

---

### Interpretation

Policy coefficients now represent **within-state changes in incident risk**, after accounting for nationwide year shocks and state-specific baselines.

This is the core risk specification for the project.

---

### Methodological Implication

The TWFE risk model improves identification by separating policy timing from broad national trend movement. Results should still be interpreted as associative rather than causal because policy adoption may respond to prior incidents.

In [97]:
formula = """
incident_count ~ 
background_check_law +
permit_to_purchase_law +
prohibited_possessor_law +
waiting_period_law +
registration_law +
child_access_law +
safety_training_law +
report_stolen_lost_law +
firearm_sales_retrictions_law +
k12_settings_law +
C(State) +
C(Year)
"""

model_twfe = smf.glm(
    formula=formula,
    data=merged_df_table,
    family=sm.families.NegativeBinomial(),
    offset=merged_df_table["log_enrollment"]
).fit()

print(model_twfe.summary())

/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:         incident_count   No. Observations:                 1989
Model:                            GLM   Df Residuals:                     1890
Model Family:        NegativeBinomial   Df Model:                           98
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2247.4
Date:                Wed, 08 Apr 2026   Deviance:                       1055.1
Time:                        12:47:52   Pearson chi2:                 1.36e+03
No. Iterations:                     9   Pseudo R-squ. (CS):             0.4500
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                       -15.0842      0.591    -25.524      0.000     -16.243     -13.926
C(State)[T.AL]                    0.6980      0.534      1.307      0.191      -0.349       1.745
C(State)[T.AR]                    0.2997      0.546      0.549      0.583      -0.771       1.370
C(State)[T.AZ]                   -0.5102      0.548     -0.931      0.352      -1.585       0.564
C(State)[T.CA]                    0.3736      0.551      0.678      0.498      -0.706       1.453
C(State)[T.CO]                    0.0651      0.558      0.117      0.907      -1.028       1.159
C(State)[T.CT]                    0.1226      0.593      0.207      0.836      -1.039       1.284
C(State)[T.DC]                    2.8558      0.582      4.911      0.000       1.716       3.996
C(State)[T.DE]                    1.0582      0.592      1.788      0.074      -0.102       2.218
C(State)[T.FL]                    0.3895      0.538      0.724      0.469      -0.665       1.444
C(State)[T.GA]                    0.4995      0.547      0.912      0.362      -0.573       1.572
C(State)[T.HI]                   -0.2006      0.713     -0.281      0.779      -1.599       1.198
C(State)[T.IA]                   -0.1762      0.585     -0.301      0.763      -1.324       0.971
C(State)[T.ID]                    0.1150      0.612      0.188      0.851      -1.085       1.315
C(State)[T.IL]                    0.4333      0.540      0.803      0.422      -0.625       1.492
C(State)[T.IN]                    0.0874      0.558      0.157      0.875      -1.006       1.180
C(State)[T.KS]                    0.2220      0.558      0.398      0.691      -0.871       1.315
C(State)[T.KY]                    0.1306      0.570      0.229      0.819      -0.986       1.247
C(State)[T.LA]                    1.1644      0.527      2.208      0.027       0.131       2.198
C(State)[T.MA]                   -0.1887      0.602     -0.313      0.754      -1.369       0.992
C(State)[T.MD]                    0.5033      0.550      0.916      0.360      -0.574       1.580
C(State)[T.ME]                   -0.3321      0.654     -0.508      0.611      -1.613       0.949
C(State)[T.MI]                    0.7587      0.539      1.407      0.159      -0.298       1.815
C(State)[T.MN]                   -0.3871      0.573     -0.676      0.499      -1.510       0.736
C(State)[T.MO]                    0.1032      0.552      0.187      0.852      -0.978       1.185
C(State)[T.MS]                    0.6270      0.564      1.111      0.267      -0.479       1.733
C(State)[T.MT]                    0.4839      0.616      0.786      0.432      -0.723       1.691
C(State)[T.NC]                    0.3403      0.540      0.631      0.528      -0.717       1.398
C(State)[T.ND]                   -0.4223      0.735     -0.574      0.566      -1.863       1.018
C(State)[T.NE]                    0.1139      0.592      0.192      0.847      -1.046       1.274
C(State)[T.NH]                   -0.1655      0.650     -0.254      0.799      -1.440       1.109
C(State)[T.NJ]                   -0.5505      0.582     -0.945      0.345      -1.692       0.591
C(State)[T.NM]                    0.4722      0.584      0.808      0.419      -0.672       1.617
C(State)[T.NV]                    0.1358      0.581      0.234      0.815      -1.003       1.274
C(State)[T.NY]                    0.1009      0.547      0.184      0.854      -0.972       1.174
C(State)[T.OH]                    0.5449      0.541      1.007      0.314      -0.516       1.605
C(State)[T.OK]                   -0.0431      0.559     -0.077      0.939      -1.138       1.052
C(State)[T.OR]                    0.2283      0.551      0.414      0.679      -0.851       1.308
C(State)[T.PA]                    0.3376      0.536      0.630      0.528      -0.712       1.387
C(State)[T.RI]                    0.3169      0.678      0.467      0.640      -1.013       1.646
C(State)[T.SC]                    0.5645      0.527      1.072      0.284      -0.467       1.597
C(State)[T.SD]                    0.1271      0.673      0.189      0.850      -1.192       1.446
C(State)[T.TN]                    0.8612      0.549      1.569      0.117      -0.215       1.937
C(State)[T.TX]                    0.2495      0.522      0.478      0.633      -0.774       1.273
C(State)[T.UT]                    0.1918      0.563      0.341      0.733      -0.911       1.295
C(State)[T.VA]                   -0.0816      0.564     -0.145      0.885      -1.187       1.024
C(State)[T.VT]                    0.2243      0.706      0.318      0.751      -1.160       1.609
C(State)[T.WA]                    0.4355      0.530      0.822      0.411      -0.602       1.473
C(State)[T.WI]                   -0.1868      0.561     -0.333      0.739      -1.286       0.912
C(State)[T.WV]                   -0.5434      0.635     -0.856      0.392      -1.788       0.701
C(State)[T.WY]                   -1.2654      1.119     -1.131      0.258      -3.459       0.928
C(Year)[T.1988]                   0.2780      0.401      0.693      0.488      -0.509       1.065
C(Year)[T.1989]                  -0.2015      0.432     -0.467      0.641      -1.047       0.644
C(Year)[T.1990]                  -0.1332      0.428     -0.311      0.755      -0.972       0.705
C(Year)[T.1991]                   0.1722      0.408      0.422      0.673      -0.627       0.971
C(Year)[T.1992]                   0.2752      0.401      0.686      0.493      -0.511       1.061
C(Year)[T.1993]                   0.7839      0.379      2.066      0.039       0.040       1.528
C(Year)[T.1994]                   0.6685      0.438      1.527      0.127      -0.189       1.526
C(Year)[T.1995]                   0.2476      0.457      0.542      0.588      -0.648       1.143
C(Year)[T.1996]                   0.0447      0.467      0.096      0.924      -0.871       0.960
C(Year)[T.1997]                   0.1083      0.463      0.234      0.815      -0.799       1.016
C(Year)[T.1998]                   0.4787      0.446      1.073      0.283      -0.396       1.353
C(Year)[T.1999]                   0.2091      0.457      0.457      0.648      -0.687       1.106
C(Year)[T.2000]                   0.3440      0.452      0.761      0.447      -0.542       1.230
C(Year)[T.2001]                   0.0648      0.466      0.139      0.890      -0.849       0.979
C(Year)[T.2002]                  -0.1405      0.478     -0.294      0.769      -1.077       0.796
C(Year)[T.2003]                   0.5693      0.443      1.285      0.199      -0.299       1.437
C(Year)[T.2004]                   0.4788      0.446      1.073      0.283      -0.395       1.353
C(Year)[T.2005]                   0.7859      0.418      1.881      0.060      -0.033       1.605
C(Year)[T.2006]                   1.1090      0.409      2.715      0.007       0.308       1.910
C(Year)[T.2007]                   0.7063      0.423      1.670      0.095      -0.122       1.535
C(Year)[T.2008]                   0.4575      0.434      1.054      0.292      -0.393       1.308
C(Year)[T.2009]                   0.4443      0.436      1.019      0.308      -0.411       1.299
C(Year)[T.2010]                  -0.2678      0.476     -0.562      0.574      -1.201       0.666
C(Year)[T.2011]                  -0.2781      0.477     -0.583      0.560      -1.213       0.657
C(Year)[T.2012]                   0.0113      0.458      0.025      0.980      -0.886       0.909
C(Year)[T.2013]                   0.4475      0.440      1.018      0.309      -0.414       1.309
C(Year)[T.2014]                   1.0450      0.420      2.488      0.013       0.222       1.868
C(Year)[T.2015]                   0.7009      0.431      1.626      0.104      -0.144       1.546
C(Year)[T.2016]                   1.0338      0.421      2.454      0.014       0.208       1.860
C(Year)[T.2017]                   1.0432      0.422      2.474      0.013       0.217       1.870
C(Year)[T.2018]                   2.0415      0.405      5.045      0.000       1.248       2.835
C(Year)[T.2019]                   1.9863      0.409      4.857      0.000       1.185       2.788
C(Year)[T.2020]                   1.8622      0.411      4.530      0.000       1.057       2.668
C(Year)[T.2021]                   2.7623      0.404      6.834      0.000       1.970       3.554
C(Year)[T.2022]                   2.9615      0.405      7.317      0.000       2.168       3.755
C(Year)[T.2023]                   3.0774      0.406      7.572      0.000       2.281       3.874
C(Year)[T.2024]                   3.1400      0.401      7.839      0.000       2.355       3.925
C(Year)[T.2025]                   2.1758      0.409      5.316      0.000       1.374       2.978
background_check_law             -0.4003      0.236     -1.697      0.090      -0.863       0.062
permit_to_purchase_law            0.2398      0.168      1.431      0.152      -0.089       0.568
prohibited_possessor_law          0.2047      0.160      1.280      0.200      -0.109       0.518
waiting_period_law               -1.4190      1.046     -1.356      0.175      -3.470       0.632
registration_law                  1.6531      1.053      1.570      0.117      -0.411       3.717
child_access_law                  0.0445      0.159      0.281      0.779      -0.266       0.355
safety_training_law              -0.1156      0.226     -0.512      0.608      -0.558       0.327
report_stolen_lost_law           -0.3031      0.175     -1.728      0.084      -0.647       0.041
firearm_sales_retrictions_law     0.0096      0.171      0.056      0.955      -0.325       0.344
k12_settings_law                 -0.3961      0.259     -1.527      0.127      -0.905       0.112
=================================================================================================

## Cluster-Robust Inference (State-Level)

### Why Cluster Standard Errors?

This is a state × year panel, so errors can be serially correlated within states across years.
Clustering by state accounts for within-state dependence in the residual process.
This changes inference (standard errors and p-values), not coefficient point estimates.
State-clustered standard errors are typically more conservative and methodologically appropriate for this panel structure.

In [98]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm

# ================================
# STEP 1 — Fit Poisson TWFE Model
# ================================

model_twfe = smf.glm(
    formula=formula,
    data=merged_df_table,
    family=sm.families.Poisson(),
    offset=merged_df_table["log_enrollment"]
).fit()

# ================================
# STEP 2 — Fit Clustered Version
# ================================

model_twfe_cluster = smf.glm(
    formula=formula,
    data=merged_df_table,
    family=sm.families.Poisson(),
    offset=merged_df_table["log_enrollment"]
).fit(
    cov_type="cluster",
    cov_kwds={"groups": merged_df_table["State"]}
)

print("Two-Way FE Poisson with State-Clustered SE")
print(model_twfe_cluster.summary())

# ================================
# STEP 3 — Policy-Only Comparison
# ================================

policy_variables = [v for v in model_twfe.params.index if v.endswith("_law")]

se_comparison = pd.DataFrame({
    "variable": policy_variables,
    "coef": [model_twfe.params[v] for v in policy_variables],
    "se_nonclustered": [model_twfe.bse[v] for v in policy_variables],
    "se_clustered": [model_twfe_cluster.bse[v] for v in policy_variables],
    "p_nonclustered": [model_twfe.pvalues[v] for v in policy_variables],
    "p_clustered": [model_twfe_cluster.pvalues[v] for v in policy_variables],
})

print("\nStandard Error Comparison")
print(se_comparison)

Two-Way FE Poisson with State-Clustered SE
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:         incident_count   No. Observations:                 1989
Model:                            GLM   Df Residuals:                     1890
Model Family:                 Poisson   Df Model:                           98
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2072.7
Date:                Wed, 08 Apr 2026   Deviance:                       1831.5
Time:                        12:47:57   Pearson chi2:                 2.22e+03
No. Iterations:                     8   Pseudo R-squ. (CS):             0.8208
Covariance Type:              cluster
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
Intercept                       -14.9519      0.271    -55.224      0.000     -15.483     -14.421
C(State)[T.AL]                    0.6778      0.064     10.644      0.000       0.553       0.803
C(State)[T.AR]                    0.3720      0.032     11.742      0.000       0.310       0.434
C(State)[T.AZ]                   -0.4826      0.013    -37.252      0.000      -0.508      -0.457
C(State)[T.CA]                   -0.0826      0.138     -0.598      0.550      -0.353       0.188
C(State)[T.CO]                    0.1662      0.091      1.817      0.069      -0.013       0.345
C(State)[T.CT]                   -0.0871      0.133     -0.656      0.512      -0.347       0.173
C(State)[T.DC]                    2.8576      0.137     20.878      0.000       2.589       3.126
C(State)[T.DE]                    1.1707      0.071     16.550      0.000       1.032       1.309
C(State)[T.FL]                    0.2025      0.081      2.505      0.012       0.044       0.361
C(State)[T.GA]                    0.5543      0.111      5.006      0.000       0.337       0.771
C(State)[T.HI]                   -0.1002      0.157     -0.638      0.523      -0.408       0.208
C(State)[T.IA]                   -0.1793      0.079     -2.263      0.024      -0.335      -0.024
C(State)[T.ID]                    0.0657      0.104      0.632      0.527      -0.138       0.269
C(State)[T.IL]                    0.3890      0.092      4.237      0.000       0.209       0.569
C(State)[T.IN]                    0.1292      0.085      1.521      0.128      -0.037       0.296
C(State)[T.KS]                    0.3377      0.029     11.604      0.000       0.281       0.395
C(State)[T.KY]                    0.2089      0.110      1.907      0.056      -0.006       0.424
C(State)[T.LA]                    1.0372      0.024     43.419      0.000       0.990       1.084
C(State)[T.MA]                   -0.2199      0.144     -1.526      0.127      -0.502       0.063
C(State)[T.MD]                    0.6130      0.109      5.637      0.000       0.400       0.826
C(State)[T.ME]                   -0.2435      0.056     -4.363      0.000      -0.353      -0.134
C(State)[T.MI]                    0.4863      0.064      7.561      0.000       0.360       0.612
C(State)[T.MN]                   -0.2518      0.108     -2.326      0.020      -0.464      -0.040
C(State)[T.MO]                    0.2704      0.093      2.909      0.004       0.088       0.453
C(State)[T.MS]                    0.6767      0.110      6.127      0.000       0.460       0.893
C(State)[T.MT]                    0.3555      0.024     14.979      0.000       0.309       0.402
C(State)[T.NC]                    0.3493      0.083      4.216      0.000       0.187       0.512
C(State)[T.ND]                   -0.3277      0.051     -6.442      0.000      -0.427      -0.228
C(State)[T.NE]                    0.0822      0.063      1.313      0.189      -0.040       0.205
C(State)[T.NH]                   -0.2377      0.079     -3.018      0.003      -0.392      -0.083
C(State)[T.NJ]                   -0.5139      0.118     -4.357      0.000      -0.745      -0.283
C(State)[T.NM]                    0.7047      0.123      5.719      0.000       0.463       0.946
C(State)[T.NV]                    0.0768      0.083      0.928      0.353      -0.085       0.239
C(State)[T.NY]                    0.2489      0.141      1.766      0.077      -0.027       0.525
C(State)[T.OH]                    0.6339      0.076      8.294      0.000       0.484       0.784
C(State)[T.OK]                   -0.0772      0.073     -1.058      0.290      -0.220       0.066
C(State)[T.OR]                    0.3708      0.046      8.012      0.000       0.280       0.461
C(State)[T.PA]                    0.3823      0.077      4.996      0.000       0.232       0.532
C(State)[T.RI]                    0.0628      0.173      0.362      0.717      -0.277       0.403
C(State)[T.SC]                    0.5326      0.023     22.997      0.000       0.487       0.578
C(State)[T.SD]                    0.1751      0.041      4.287      0.000       0.095       0.255
C(State)[T.TN]                    1.0696      0.081     13.132      0.000       0.910       1.229
C(State)[T.TX]                    0.0765      0.076      1.012      0.312      -0.072       0.225
C(State)[T.UT]                   -0.0262      0.076     -0.345      0.730      -0.175       0.123
C(State)[T.VA]                    0.0812      0.083      0.978      0.328      -0.081       0.244
C(State)[T.VT]                    0.4138      0.070      5.886      0.000       0.276       0.552
C(State)[T.WA]                    0.3549      0.105      3.387      0.001       0.150       0.560
C(State)[T.WI]                    0.0345      0.083      0.415      0.678      -0.128       0.197
C(State)[T.WV]                   -0.3391      0.018    -19.234      0.000      -0.374      -0.305
C(State)[T.WY]                   -1.2195      0.043    -28.526      0.000      -1.303      -1.136
C(Year)[T.1988]                   0.2675      0.232      1.154      0.249      -0.187       0.722
C(Year)[T.1989]                  -0.3184      0.336     -0.948      0.343      -0.977       0.340
C(Year)[T.1990]                  -0.1449      0.375     -0.386      0.699      -0.881       0.591
C(Year)[T.1991]                   0.2502      0.335      0.748      0.454      -0.405       0.906
C(Year)[T.1992]                   0.3058      0.217      1.408      0.159      -0.120       0.731
C(Year)[T.1993]                   0.5716      0.284      2.016      0.044       0.016       1.127
C(Year)[T.1994]                   0.5186      0.343      1.511      0.131      -0.154       1.191
C(Year)[T.1995]                   0.0888      0.342      0.260      0.795      -0.582       0.759
C(Year)[T.1996]                  -0.1274      0.436     -0.293      0.770      -0.981       0.726
C(Year)[T.1997]                  -0.0016      0.333     -0.005      0.996      -0.654       0.651
C(Year)[T.1998]                   0.2797      0.327      0.855      0.393      -0.362       0.921
C(Year)[T.1999]                  -0.0543      0.374     -0.145      0.885      -0.788       0.679
C(Year)[T.2000]                   0.1289      0.328      0.393      0.694      -0.514       0.772
C(Year)[T.2001]                   0.0317      0.421      0.075      0.940      -0.794       0.857
C(Year)[T.2002]                  -0.2954      0.356     -0.829      0.407      -0.994       0.403
C(Year)[T.2003]                   0.2756      0.374      0.738      0.461      -0.456       1.008
C(Year)[T.2004]                   0.2958      0.379      0.781      0.435      -0.446       1.038
C(Year)[T.2005]                   0.6574      0.302      2.178      0.029       0.066       1.249
C(Year)[T.2006]                   0.7972      0.350      2.278      0.023       0.111       1.483
C(Year)[T.2007]                   0.5403      0.288      1.878      0.060      -0.024       1.104
C(Year)[T.2008]                   0.3377      0.354      0.953      0.341      -0.357       1.032
C(Year)[T.2009]                   0.1866      0.253      0.739      0.460      -0.309       0.682
C(Year)[T.2010]                  -0.5732      0.417     -1.374      0.170      -1.391       0.245
C(Year)[T.2011]                  -0.5166      0.399     -1.295      0.195      -1.299       0.266
C(Year)[T.2012]                  -0.3479      0.396     -0.878      0.380      -1.124       0.428
C(Year)[T.2013]                   0.2248      0.300      0.749      0.454      -0.363       0.813
C(Year)[T.2014]                   0.5377      0.378      1.422      0.155      -0.203       1.279
C(Year)[T.2015]                   0.4084      0.399      1.023      0.307      -0.374       1.191
C(Year)[T.2016]                   0.6135      0.331      1.856      0.063      -0.034       1.261
C(Year)[T.2017]                   0.7849      0.302      2.595      0.009       0.192       1.378
C(Year)[T.2018]                   1.5689      0.335      4.686      0.000       0.913       2.225
C(Year)[T.2019]                   1.6190      0.334      4.848      0.000       0.965       2.274
C(Year)[T.2020]                   1.5697      0.318      4.935      0.000       0.946       2.193
C(Year)[T.2021]                   2.4072      0.302      7.967      0.000       1.815       2.999
C(Year)[T.2022]                   2.5945      0.328      7.908      0.000       1.951       3.237
C(Year)[T.2023]                   2.7228      0.329      8.274      0.000       2.078       3.368
C(Year)[T.2024]                   2.8821      0.288     10.011      0.000       2.318       3.446
C(Year)[T.2025]                   2.0568      0.296      6.943      0.000       1.476       2.637
background_check_law             -0.3588      0.239     -1.504      0.133      -0.826       0.109
permit_to_purchase_law            0.3640      0.142      2.567      0.010       0.086       0.642
prohibited_possessor_law          0.2183      0.137      1.591      0.112      -0.051       0.487
waiting_period_law               -1.5592      1.360     -1.147      0.251      -4.224       1.106
registration_law                  1.6809      1.360      1.236      0.216      -0.984       4.346
child_access_law                  0.0891      0.096      0.929      0.353      -0.099       0.277
safety_training_law              -0.0021      0.196     -0.011      0.992      -0.385       0.381
report_stolen_lost_law           -0.1187      0.085     -1.398      0.162      -0.285       0.048
firearm_sales_retrictions_law    -0.0099      0.121     -0.082      0.935      -0.246       0.226
k12_settings_law                 -0.4256      0.076     -5.575      0.000      -0.575      -0.276
=================================================================================================

Standard Error Comparison
                        variable      coef  se_nonclustered  se_clustered  \
0           background_check_law -0.358756         0.161599      0.238505
1         permit_to_purchase_law  0.364005         0.101853      0.141802
2       prohibited_possessor_law  0.218298         0.099623      0.137222
3             waiting_period_law -1.559249         1.012120      1.359592
4               registration_law  1.680946         1.013781      1.359837
5               child_access_law  0.089090         0.084205      0.095889
6            safety_training_law -0.002067         0.114117      0.195577
7         report_stolen_lost_law -0.118707         0.091157      0.084920
8  firearm_sales_retrictions_law -0.009880         0.095825      0.120541
9               k12_settings_law -0.425606         0.105697      0.076346

   p_nonclustered   p_clustered
0        0.026416  1.325332e-01
1        0.000352  1.025853e-02
2        0.028434  1.116462e-01
3        0.123420  2.514433e-01
4        0.097298  2.164073e-01
5        0.290051  3.528406e-01
6        0.985548  9.915669e-01
7        0.192838  1.621554e-01
8        0.917878  9.346737e-01
9        0.000057  2.479219e-08

## Lag the policy variables.

We test whether policy adoption predicts future incident risk rather than same-year effects.

In [99]:
policy_cols = [
    "background_check_law",
    "permit_to_purchase_law",
    "prohibited_possessor_law",
    "waiting_period_law",
    "registration_law",
    "child_access_law",
    "safety_training_law",
    "report_stolen_lost_law",
    "firearm_sales_retrictions_law",
    "k12_settings_law"
]

# sort properly first
merged_df_table = merged_df_table.sort_values(["State", "Year"])

# create 1-year lags within state
for col in policy_cols:
    merged_df_table[col + "_lag1"] = (
        merged_df_table.groupby("State")[col].shift(1)
    )

print(
    merged_df_table[[c for c in merged_df_table.columns if "_lag1" in c]].isna().sum().head()
)

background_check_law_lag1        51
permit_to_purchase_law_lag1      51
prohibited_possessor_law_lag1    51
waiting_period_law_lag1          51
registration_law_lag1            51
dtype: int64

In [100]:
lag_cols = [col for col in merged_df_table.columns if col.endswith("_lag1")]

merged_df_table[lag_cols] = merged_df_table[lag_cols].fillna(0)

print(merged_df_table[lag_cols].isna().sum().sum())

0

Notice the Year coefficients:

2018–2024 effects are extremely large and significant.

This indicates:

National upward structural shift in incidents dominates policy variation.

That is your strongest empirical finding so far.

evidence currently supports:

Strong national time dynamics

Weak within-state short-run policy effects

Significant endogeneity concerns

That is a legitimate, publishable conclusion if framed correctly.

In [101]:
formula_lag = """
incident_count ~ 
background_check_law_lag1 +
permit_to_purchase_law_lag1 +
prohibited_possessor_law_lag1 +
waiting_period_law_lag1 +
registration_law_lag1 +
child_access_law_lag1 +
safety_training_law_lag1 +
report_stolen_lost_law_lag1 +
firearm_sales_retrictions_law_lag1 +
k12_settings_law_lag1 +
C(State) +
C(Year)
"""

model_twfe_lag = smf.glm(
    formula=formula_lag,
    data=merged_df_table,
    family=sm.families.NegativeBinomial(),
    offset=merged_df_table["log_enrollment"]
).fit()

print(model_twfe_lag.summary())

/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:         incident_count   No. Observations:                 1989
Model:                            GLM   Df Residuals:                     1890
Model Family:        NegativeBinomial   Df Model:                           98
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -2251.4
Date:                Wed, 08 Apr 2026   Deviance:                       1063.2
Time:                        12:47:58   Pearson chi2:                 1.34e+03
No. Iterations:                     9   Pseudo R-squ. (CS):             0.4478
Covariance Type:            nonrobust
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
Intercept                            -14.7716      0.567    -26.041      0.000     -15.883     -13.660
C(State)[T.AL]                         0.7263      0.536      1.356      0.175      -0.324       1.776
C(State)[T.AR]                         0.3519      0.548      0.642      0.521      -0.722       1.425
C(State)[T.AZ]                        -0.4949      0.548     -0.903      0.367      -1.569       0.580
C(State)[T.CA]                         0.2970      0.559      0.532      0.595      -0.798       1.392
C(State)[T.CO]                         0.1004      0.563      0.178      0.858      -1.003       1.204
C(State)[T.CT]                         0.0504      0.603      0.084      0.933      -1.131       1.231
C(State)[T.DC]                         2.7081      0.591      4.579      0.000       1.549       3.867
C(State)[T.DE]                         1.0400      0.599      1.736      0.083      -0.134       2.214
C(State)[T.FL]                         0.3835      0.545      0.704      0.481      -0.684       1.451
C(State)[T.GA]                         0.3996      0.553      0.723      0.470      -0.684       1.483
C(State)[T.HI]                        -0.2247      0.720     -0.312      0.755      -1.636       1.186
C(State)[T.IA]                        -0.1931      0.591     -0.327      0.744      -1.351       0.965
C(State)[T.ID]                         0.0317      0.615      0.052      0.959      -1.174       1.237
C(State)[T.IL]                         0.4267      0.546      0.782      0.434      -0.643       1.496
C(State)[T.IN]                         0.0592      0.562      0.105      0.916      -1.043       1.162
C(State)[T.KS]                         0.1728      0.557      0.310      0.756      -0.919       1.264
C(State)[T.KY]                         0.0360      0.575      0.063      0.950      -1.092       1.164
C(State)[T.LA]                         1.0957      0.526      2.082      0.037       0.064       2.127
C(State)[T.MA]                        -0.3555      0.613     -0.580      0.562      -1.556       0.845
C(State)[T.MD]                         0.5067      0.557      0.909      0.363      -0.586       1.599
C(State)[T.ME]                        -0.2825      0.656     -0.430      0.667      -1.569       1.004
C(State)[T.MI]                         0.6554      0.543      1.208      0.227      -0.408       1.719
C(State)[T.MN]                        -0.2815      0.579     -0.486      0.627      -1.416       0.853
C(State)[T.MO]                         0.0695      0.557      0.125      0.901      -1.022       1.161
C(State)[T.MS]                         0.5321      0.570      0.934      0.350      -0.585       1.649
C(State)[T.MT]                         0.4333      0.617      0.703      0.482      -0.776       1.642
C(State)[T.NC]                         0.3615      0.545      0.664      0.507      -0.706       1.429
C(State)[T.ND]                        -0.3592      0.737     -0.488      0.626      -1.803       1.084
C(State)[T.NE]                         0.0872      0.594      0.147      0.883      -1.077       1.251
C(State)[T.NH]                        -0.1465      0.654     -0.224      0.823      -1.429       1.136
C(State)[T.NJ]                        -0.5901      0.591     -0.998      0.318      -1.748       0.568
C(State)[T.NM]                         0.4089      0.590      0.693      0.488      -0.747       1.565
C(State)[T.NV]                         0.1574      0.587      0.268      0.789      -0.993       1.308
C(State)[T.NY]                         0.0254      0.552      0.046      0.963      -1.056       1.107
C(State)[T.OH]                         0.3950      0.543      0.727      0.467      -0.670       1.460
C(State)[T.OK]                        -0.0575      0.562     -0.102      0.919      -1.159       1.044
C(State)[T.OR]                         0.2343      0.554      0.423      0.672      -0.851       1.320
C(State)[T.PA]                         0.2964      0.541      0.548      0.584      -0.764       1.357
C(State)[T.RI]                         0.1779      0.691      0.257      0.797      -1.177       1.533
C(State)[T.SC]                         0.6443      0.526      1.224      0.221      -0.387       1.676
C(State)[T.SD]                         0.1260      0.675      0.187      0.852      -1.198       1.450
C(State)[T.TN]                         0.8110      0.555      1.461      0.144      -0.277       1.899
C(State)[T.TX]                         0.2261      0.526      0.430      0.667      -0.805       1.257
C(State)[T.UT]                         0.1408      0.565      0.249      0.803      -0.967       1.249
C(State)[T.VA]                        -0.1349      0.571     -0.236      0.813      -1.253       0.984
C(State)[T.VT]                         0.3200      0.704      0.455      0.649      -1.059       1.699
C(State)[T.WA]                         0.4733      0.532      0.890      0.374      -0.570       1.516
C(State)[T.WI]                        -0.1717      0.566     -0.303      0.762      -1.282       0.938
C(State)[T.WV]                        -0.5375      0.636     -0.845      0.398      -1.784       0.709
C(State)[T.WY]                        -1.3091      1.121     -1.167      0.243      -3.507       0.889
C(Year)[T.1988]                        0.1488      0.454      0.328      0.743      -0.741       1.038
C(Year)[T.1989]                       -0.3388      0.482     -0.702      0.482      -1.284       0.607
C(Year)[T.1990]                       -0.2966      0.481     -0.617      0.537      -1.239       0.646
C(Year)[T.1991]                        0.0405      0.466      0.087      0.931      -0.872       0.953
C(Year)[T.1992]                        0.1472      0.464      0.317      0.751      -0.762       1.056
C(Year)[T.1993]                        0.6442      0.445      1.447      0.148      -0.228       1.517
C(Year)[T.1994]                        0.3378      0.456      0.740      0.459      -0.556       1.232
C(Year)[T.1995]                        0.1125      0.531      0.212      0.832      -0.927       1.152
C(Year)[T.1996]                       -0.0720      0.541     -0.133      0.894      -1.132       0.988
C(Year)[T.1997]                       -0.0250      0.539     -0.046      0.963      -1.082       1.032
C(Year)[T.1998]                        0.3526      0.524      0.673      0.501      -0.674       1.379
C(Year)[T.1999]                        0.1299      0.534      0.243      0.808      -0.916       1.176
C(Year)[T.2000]                        0.2097      0.531      0.395      0.693      -0.831       1.250
C(Year)[T.2001]                       -0.0665      0.545     -0.122      0.903      -1.134       1.001
C(Year)[T.2002]                       -0.2791      0.556     -0.502      0.616      -1.369       0.811
C(Year)[T.2003]                        0.4319      0.527      0.820      0.412      -0.600       1.464
C(Year)[T.2004]                        0.3327      0.530      0.628      0.530      -0.706       1.371
C(Year)[T.2005]                        0.6361      0.521      1.220      0.222      -0.385       1.658
C(Year)[T.2006]                        0.9048      0.504      1.797      0.072      -0.082       1.892
C(Year)[T.2007]                        0.4831      0.513      0.941      0.347      -0.523       1.489
C(Year)[T.2008]                        0.2203      0.520      0.424      0.672      -0.799       1.240
C(Year)[T.2009]                        0.2094      0.519      0.404      0.686      -0.807       1.226
C(Year)[T.2010]                       -0.4927      0.552     -0.892      0.372      -1.575       0.589
C(Year)[T.2011]                       -0.4952      0.552     -0.897      0.370      -1.577       0.587
C(Year)[T.2012]                       -0.2131      0.537     -0.397      0.692      -1.266       0.839
C(Year)[T.2013]                        0.2239      0.519      0.432      0.666      -0.793       1.241
C(Year)[T.2014]                        0.8178      0.505      1.618      0.106      -0.173       1.808
C(Year)[T.2015]                        0.4557      0.515      0.885      0.376      -0.554       1.465
C(Year)[T.2016]                        0.7971      0.506      1.576      0.115      -0.194       1.788
C(Year)[T.2017]                        0.7945      0.506      1.571      0.116      -0.197       1.786
C(Year)[T.2018]                        1.7762      0.492      3.611      0.000       0.812       2.740
C(Year)[T.2019]                        1.7421      0.494      3.527      0.000       0.774       2.710
C(Year)[T.2020]                        1.5933      0.498      3.198      0.001       0.617       2.570
C(Year)[T.2021]                        2.4946      0.490      5.091      0.000       1.534       3.455
C(Year)[T.2022]                        2.6912      0.491      5.479      0.000       1.729       3.654
C(Year)[T.2023]                        2.8115      0.490      5.735      0.000       1.851       3.772
C(Year)[T.2024]                        2.8813      0.492      5.855      0.000       1.917       3.846
C(Year)[T.2025]                        1.8944      0.346      5.468      0.000       1.215       2.573
background_check_law_lag1             -0.2501      0.229     -1.090      0.276      -0.700       0.200
permit_to_purchase_law_lag1            0.1555      0.168      0.927      0.354      -0.173       0.484
prohibited_possessor_law_lag1          0.0908      0.160      0.567      0.571      -0.223       0.405
waiting_period_law_lag1               -1.5456      1.114     -1.387      0.165      -3.729       0.638
registration_law_lag1                  1.6795      1.121      1.498      0.134      -0.518       3.877
child_access_law_lag1                  0.0641      0.163      0.393      0.695      -0.256       0.384
safety_training_law_lag1              -0.0350      0.230     -0.152      0.879      -0.485       0.415
report_stolen_lost_law_lag1           -0.1372      0.178     -0.771      0.441      -0.486       0.212
firearm_sales_retrictions_law_lag1    -0.0926      0.170     -0.543      0.587      -0.427       0.241
k12_settings_law_lag1                 -0.2623      0.255     -1.027      0.304      -0.763       0.238
======================================================================================================

## Risk-Only Scope

The notebook remains limited to enrollment-adjusted incident risk models.

- Primary outcome: `incident_count`  
- Exposure adjustment: `log(total_students)` offset  
- Substantive target: lower risk of incident occurrence  

Severity outcomes such as `total_victims` and `victims_per_incident` are excluded from the main modeling framework.

## DC Exclusion Robustness Check

Refit the negative binomial risk models after excluding DC and compare policy coefficients across the full sample and the no-DC sample.

The two non-lag negative binomial cells above use the same specification, so the DC robustness refit is reported once for that specification.

The final comparison table below includes only:

- `nb_twfe`
- `nb_twfe_lagged`

In [102]:
from IPython.display import display

merged_df_table_no_dc = merged_df_table[merged_df_table["State"] != "DC"].copy()

sample_comparison = pd.DataFrame(
    {
        "sample": ["full", "no_dc"],
        "observations": [len(merged_df_table), len(merged_df_table_no_dc)],
        "states": [merged_df_table["State"].nunique(), merged_df_table_no_dc["State"].nunique()],
    }
)

def fit_risk_glm(formula_text, data, family, cluster=False):
    glm = smf.glm(
        formula=formula_text,
        data=data,
        family=family,
        offset=data["log_enrollment"],
    )
    if cluster:
        return glm.fit(cov_type="cluster", cov_kwds={"groups": data["State"]})
    return glm.fit()

def compare_policy_coefficients(full_model, no_dc_model, terms, model_name):
    comparison = pd.DataFrame(
        {
            "model": model_name,
            "term": terms,
            "coef_full": full_model.params.reindex(terms).values,
            "coef_no_dc": no_dc_model.params.reindex(terms).values,
            "irr_full": np.exp(full_model.params.reindex(terms).values),
            "irr_no_dc": np.exp(no_dc_model.params.reindex(terms).values),
            "p_full": full_model.pvalues.reindex(terms).values,
            "p_no_dc": no_dc_model.pvalues.reindex(terms).values,
        }
    )
    comparison["delta_coef"] = comparison["coef_no_dc"] - comparison["coef_full"]
    comparison["sig_full_5pct"] = comparison["p_full"] < 0.05
    comparison["sig_no_dc_5pct"] = comparison["p_no_dc"] < 0.05
    return comparison

display(sample_comparison)

  sample  observations  states
0   full          1989      51
1  no_dc          1950      50

In [103]:
model_nb_full = fit_risk_glm(formula, merged_df_table, sm.families.NegativeBinomial())
model_nb_no_dc = fit_risk_glm(formula, merged_df_table_no_dc, sm.families.NegativeBinomial())

model_lag_full = fit_risk_glm(formula_lag, merged_df_table, sm.families.NegativeBinomial())
model_lag_no_dc = fit_risk_glm(formula_lag, merged_df_table_no_dc, sm.families.NegativeBinomial())

/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "
/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "
/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "
/home/tommie-clark/capstoneProje t/capstoneProject2026/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [104]:
base_policy_terms = [term for term in model_nb_full.params.index if term.endswith("_law")]
lag_policy_terms = [term for term in model_lag_full.params.index if term.endswith("_law_lag1")]

combined_policy_comparison = pd.concat(
    [
        compare_policy_coefficients(model_nb_full, model_nb_no_dc, base_policy_terms, "nb_twfe"),
        compare_policy_coefficients(model_lag_full, model_lag_no_dc, lag_policy_terms, "nb_twfe_lagged"),
    ],
    ignore_index=True,
)

combined_policy_comparison["abs_delta_coef"] = combined_policy_comparison["delta_coef"].abs()
combined_policy_comparison = combined_policy_comparison.sort_values(["model", "abs_delta_coef"], ascending=[True, False])

significance_change_summary = combined_policy_comparison[
    combined_policy_comparison["sig_full_5pct"] != combined_policy_comparison["sig_no_dc_5pct"]
].copy()

policy_signal_summary = combined_policy_comparison[
    combined_policy_comparison["sig_full_5pct"] | combined_policy_comparison["sig_no_dc_5pct"]
].copy()

display(combined_policy_comparison.round(4))
display(significance_change_summary.round(4))
display(policy_signal_summary.round(4))

,model,term,coef_full,coef_no_dc,irr_full,irr_no_dc,p_full,p_no_dc,delta_coef,sig_full_5pct,sig_no_dc_5pct,abs_delta_coef
6,nb_twfe,safety_training_law,-0.1156,0.0327,0.8909,1.0332,0.6085,0.8934,0.1482,False,False,0.1482
7,nb_twfe,report_stolen_lost_law,-0.3031,-0.3673,0.7385,0.6926,0.0839,0.0406,-0.0641,False,True,0.0641
8,nb_twfe,firearm_sales_retrictions_law,0.0096,0.0659,1.0097,1.0682,0.9549,0.7039,0.0563,False,False,0.0563
3,nb_twfe,waiting_period_law,-1.4190,-1.3837,0.2420,0.2506,0.1751,0.1862,0.0353,False,False,0.0353
4,nb_twfe,registration_law,1.6531,1.6201,5.2233,5.0537,0.1165,0.1241,-0.0330,False,False,0.0330
2,nb_twfe,prohibited_possessor_law,0.2047,0.1879,1.2272,1.2067,0.2004,0.2413,-0.0169,False,False,0.0169
9,nb_twfe,k12_settings_law,-0.3961,-0.3811,0.6729,0.6831,0.1268,0.1422,0.0150,False,False,0.0150
0,nb_twfe,background_check_law,-0.4003,-0.3863,0.6701,0.6796,0.0897,0.1055,0.0141,False,False,0.0141
5,nb_twfe,child_access_law,0.0445,0.0326,1.0455,1.0331,0.7787,0.8387,-0.0119,False,False,0.0119
1,nb_twfe,permit_to_purchase_law,0.2398,0.2515,1.2710,1.2860,0.1523,0.1374,0.0118,False,False,0.0118
16,nb_twfe_lagged,safety_training_law_lag1,-0.0350,0.1062,0.9656,1.1120,0.8789,0.6718,0.1412,False,False,0.1412
17,nb_twfe_lagged,report_stolen_lost_law_lag1,-0.1372,-0.1935,0.8718,0.8241,0.4409,0.2872,-0.0563,False,False,0.0563
18,nb_twfe_lagged,firearm_sales_retrictions_law_lag1,-0.0926,-0.0659,0.9115,0.9362,0.5869,0.7040,0.0267,False,False,0.0267
15,nb_twfe_lagged,child_access_law_lag1,0.0641,0.0421,1.0662,1.0430,0.6947,0.7988,-0.0220,False,False,0.0220
13,nb_twfe_lagged,waiting_period_law_lag1,-1.5456,-1.5293,0.2132,0.2167,0.1654,0.1713,0.0163,False,False,0.0163
12,nb_twfe_lagged,prohibited_possessor_law_lag1,0.0908,0.0756,1.0951,1.0785,0.5707,0.6381,-0.0152,False,False,0.0152
19,nb_twfe_lagged,k12_settings_law_lag1,-0.2623,-0.2515,0.7692,0.7776,0.3045,0.3254,0.0109,False,False,0.0109
14,nb_twfe_lagged,registration_law_lag1,1.6795,1.6721,5.3628,5.3231,0.1342,0.1372,-0.0074,False,False,0.0074
10,nb_twfe_lagged,background_check_law_lag1,-0.2501,-0.2574,0.7787,0.7730,0.2757,0.2685,-0.0074,False,False,0.0074
11,nb_twfe_lagged,permit_to_purchase_law_lag1,0.1555,0.1586,1.1682,1.1719,0.3538,0.3479,0.0031,False,False,0.0031

,model,term,coef_full,coef_no_dc,irr_full,irr_no_dc,p_full,p_no_dc,delta_coef,sig_full_5pct,sig_no_dc_5pct,abs_delta_coef
7,nb_twfe,report_stolen_lost_law,-0.3031,-0.3673,0.7385,0.6926,0.0839,0.0406,-0.0641,False,True,0.0641

,model,term,coef_full,coef_no_dc,irr_full,irr_no_dc,p_full,p_no_dc,delta_coef,sig_full_5pct,sig_no_dc_5pct,abs_delta_coef
7,nb_twfe,report_stolen_lost_law,-0.3031,-0.3673,0.7385,0.6926,0.0839,0.0406,-0.0641,False,True,0.0641